// ============================================================
// Exposure2Tumor — Cancer Site Configuration
// Evidence-based exposure recipes per cancer site
// ============================================================

import { Colors } from '../theme';
import type { CancerSiteConfig, CancerSite } from '../types';

export const CANCER_SITES: Record<CancerSite, CancerSiteConfig> = {
  lung: {
    id: 'lung',
    label: 'Lung & Bronchus Cancer',
    shortLabel: 'Lung',
    color: Colors.lung,
    icon: 'lungs',
    exposureFamilies: ['environmental', 'behavioral', 'screening_access', 'social_structural', 'occupational'],
    keyMeasures: [
      'smoking_prevalence',
      'pm25_concentration',
      'radon_zone',
      'insurance_gap',
      'transportation_barriers',
      'lung_cancer_incidence',
      'lung_cancer_mortality',
      'late_stage_lung',
    ],
    description: 'Lung cancer is the leading cause of cancer death. Smoking, air pollution (PM2.5), radon, insurance gaps, and transportation barriers are key modifiable factors.',
    evidenceModel: 'lung_v1_gradient_boost',
  },
  breast: {
    id: 'breast',
    label: 'Breast Cancer',
    shortLabel: 'Breast',
    color: Colors.breast,
    icon: 'ribbon',
    exposureFamilies: ['environmental', 'behavioral', 'screening_access', 'social_structural', 'food_environment'],
    keyMeasures: [
      'mammography_rate',
      'obesity_prevalence',
      'physical_inactivity',
      'pm25_concentration',
      'transportation_barriers',
      'food_insecurity',
      'breast_cancer_incidence',
      'breast_cancer_mortality',
    ],
    description: 'Breast cancer outcomes are strongly linked to mammography access, obesity, physical inactivity, PM2.5 exposure, and structural access barriers.',
    evidenceModel: 'breast_v1_gradient_boost',
  },
  colorectal: {
    id: 'colorectal',
    label: 'Colorectal Cancer',
    shortLabel: 'Colorectal',
    color: Colors.colorectal,
    icon: 'stomach',
    exposureFamilies: ['behavioral', 'screening_access', 'food_environment', 'social_structural'],
    keyMeasures: [
      'colorectal_screening_rate',
      'obesity_prevalence',
      'physical_inactivity',
      'food_access_low',
      'food_desert_tract',
      'insurance_gap',
      'colorectal_cancer_incidence',
      'colorectal_cancer_mortality',
    ],
    description: 'Colorectal cancer is highly preventable through screening. Diet context, obesity, inactivity, and access barriers modulate community burden.',
    evidenceModel: 'colorectal_v1_gradient_boost',
  },
  melanoma: {
    id: 'melanoma',
    label: 'Melanoma of the Skin',
    shortLabel: 'Melanoma',
    color: Colors.melanoma,
    icon: 'sun',
    exposureFamilies: ['climate_uv', 'occupational', 'screening_access', 'social_structural'],
    keyMeasures: [
      'uv_exposure_index',
      'outdoor_occupation_pct',
      'dermatology_access',
      'insurance_gap',
      'melanoma_incidence',
      'melanoma_mortality',
    ],
    description: 'Melanoma risk is driven by UV exposure (solar radiation), outdoor occupational context, and access to dermatologic screening.',
    evidenceModel: 'melanoma_v1_gradient_boost',
  },
  liver: {
    id: 'liver',
    label: 'Liver & Intrahepatic Bile Duct Cancer',
    shortLabel: 'Liver',
    color: Colors.liver,
    icon: 'liver',
    exposureFamilies: ['behavioral', 'environmental', 'social_structural', 'screening_access'],
    keyMeasures: [
      'heavy_drinking_prevalence',
      'hepatitis_prevalence',
      'obesity_prevalence',
      'insurance_gap',
      'liver_cancer_incidence',
      'liver_cancer_mortality',
    ],
    description: 'Liver cancer burden relates to alcohol use, hepatitis, obesity, environmental toxicants, and structural access to hepatologic care.',
    evidenceModel: 'liver_v1_gradient_boost',
  },
  cervical: {
    id: 'cervical',
    label: 'Cervical Cancer',
    shortLabel: 'Cervical',
    color: Colors.cervical,
    icon: 'female',
    exposureFamilies: ['screening_access', 'behavioral', 'social_structural'],
    keyMeasures: [
      'cervical_screening_rate',
      'hpv_vaccination_rate',
      'insurance_gap',
      'cervical_cancer_incidence',
      'cervical_cancer_mortality',
    ],
    description: 'Cervical cancer is highly preventable via HPV vaccination and screening. Note: BRFSS screening questions changed in 2025, limiting current PLACES coverage.',
    evidenceModel: 'cervical_v1_linear',
  },
  prostate: {
    id: 'prostate',
    label: 'Prostate Cancer',
    shortLabel: 'Prostate',
    color: '#6366F1',
    icon: 'male',
    exposureFamilies: ['screening_access', 'social_structural', 'environmental', 'behavioral'],
    keyMeasures: [
      'psa_screening_rate',
      'insurance_gap',
      'prostate_cancer_incidence',
      'prostate_cancer_mortality',
    ],
    description: 'Prostate cancer outcomes reflect screening patterns, access to urologic care, and social-structural vulnerability.',
    evidenceModel: 'prostate_v1_linear',
  },
  pancreatic: {
    id: 'pancreatic',
    label: 'Pancreatic Cancer',
    shortLabel: 'Pancreatic',
    color: '#A3A3A3',
    icon: 'medical-bag',
    exposureFamilies: ['behavioral', 'social_structural', 'environmental'],
    keyMeasures: [
      'smoking_prevalence',
      'obesity_prevalence',
      'diabetes_prevalence',
      'pancreatic_cancer_incidence',
      'pancreatic_cancer_mortality',
    ],
    description: 'Pancreatic cancer has complex etiology linked to smoking, obesity, diabetes, and select environmental exposures.',
    evidenceModel: 'pancreatic_v1_linear',
  },
  kidney: {
    id: 'kidney',
    label: 'Kidney & Renal Pelvis Cancer',
    shortLabel: 'Kidney',
    color: '#EC4899',
    icon: 'kidney',
    exposureFamilies: ['behavioral', 'environmental', 'social_structural'],
    keyMeasures: [
      'smoking_prevalence',
      'obesity_prevalence',
      'hypertension_prevalence',
      'kidney_cancer_incidence',
      'kidney_cancer_mortality',
    ],
    description: 'Kidney cancer burden is linked to smoking, obesity, hypertension, and environmental chemical exposures.',
    evidenceModel: 'kidney_v1_linear',
  },
  bladder: {
    id: 'bladder',
    label: 'Bladder Cancer',
    shortLabel: 'Bladder',
    color: '#0EA5E9',
    icon: 'water',
    exposureFamilies: ['behavioral', 'environmental', 'occupational'],
    keyMeasures: [
      'smoking_prevalence',
      'industrial_chemical_exposure',
      'bladder_cancer_incidence',
      'bladder_cancer_mortality',
    ],
    description: 'Bladder cancer is strongly linked to smoking and occupational chemical exposures (aromatic amines, dyes).',
    evidenceModel: 'bladder_v1_linear',
  },
  oral: {
    id: 'oral',
    label: 'Oral Cavity & Pharynx Cancer',
    shortLabel: 'Oral',
    color: '#F43F5E',
    icon: 'emoticon-outline',
    exposureFamilies: ['behavioral', 'screening_access', 'social_structural'],
    keyMeasures: [
      'smoking_prevalence',
      'heavy_drinking_prevalence',
      'dental_access',
      'oral_cancer_incidence',
      'oral_cancer_mortality',
    ],
    description: 'Oral cancer burden relates to tobacco, alcohol, HPV, and access to dental/oral screening.',
    evidenceModel: 'oral_v1_linear',
  },
};

export const PRIMARY_SITES: CancerSite[] = ['lung', 'breast', 'colorectal', 'melanoma'];
export const SECONDARY_SITES: CancerSite[] = ['liver', 'prostate', 'cervical'];
export const ALL_SITES: CancerSite[] = Object.keys(CANCER_SITES) as CancerSite[];

export const EXPOSURE_FAMILY_LABELS: Record<string, string> = {
  environmental: 'Environmental Burden',
  behavioral: 'Behavioral Risk',
  screening_access: 'Screening & Access',
  social_structural: 'Social & Structural',
  occupational: 'Occupational',
  climate_uv: 'Climate & UV',
  food_environment: 'Food Environment',
};

export const EXPOSURE_FAMILY_COLORS: Record<string, string> = {
  environmental: Colors.environmental,
  behavioral: Colors.behavioral,
  screening_access: Colors.screeningAccess,
  social_structural: Colors.socialVulnerability,
  occupational: Colors.occupational,
  climate_uv: Colors.climateUV,
  food_environment: Colors.preventionOpportunity,
};
