// ============================================================
// Exposure2Tumor — Data Source Registry
// Full provenance for every public data source
// ============================================================

import type { DataSource } from '../types';

export const DATA_SOURCES: Record<string, DataSource> = {
  uscs: {
    id: 'uscs',
    name: 'U.S. Cancer Statistics',
    abbreviation: 'USCS',
    url: 'https://www.cdc.gov/united-states-cancer-statistics/',
    description: 'Official federal cancer statistics combining NPCR and SEER data. Includes 39M+ cancer cases since 2001.',
    publisher: 'CDC / NCI',
    vintage: '2001-2022',
    releaseDate: '2025',
    geographyLevels: ['national', 'state', 'county'],
    updateFrequency: 'Annual',
    limitations: [
      'County data may be suppressed for small populations',
      'Two-year reporting lag typical',
      'Not available below county level',
    ],
    citation: 'U.S. Cancer Statistics Working Group. U.S. Cancer Statistics Data Visualizations Tool.',
  },
  scp: {
    id: 'scp',
    name: 'State Cancer Profiles',
    abbreviation: 'SCP',
    url: 'https://statecancerprofiles.cancer.gov/',
    description: 'Geographic patterns of cancer incidence, mortality, screening, and risk factors.',
    publisher: 'NCI / CDC',
    vintage: '2018-2022',
    releaseDate: '2025',
    geographyLevels: ['national', 'state', 'county'],
    updateFrequency: 'Annual',
    limitations: [
      'County-level data suppressed when cases < 16',
      'Age-adjusted rates only',
      'Limited demographic stratification at county level',
    ],
    citation: 'State Cancer Profiles. National Cancer Institute and CDC.',
  },
  places: {
    id: 'places',
    name: 'PLACES: Local Data for Better Health',
    abbreviation: 'PLACES',
    url: 'https://www.cdc.gov/places/',
    description: '40+ health measures at county, place, tract, and ZCTA levels. Includes prevention, risk behaviors, social needs.',
    publisher: 'CDC',
    vintage: '2023',
    releaseDate: '2025-12',
    geographyLevels: ['county', 'place', 'tract', 'zcta'],
    updateFrequency: 'Annual',
    limitations: [
      'Model-based small area estimates derived from BRFSS',
      'Cervical cancer screening removed in Dec 2025 release due to BRFSS question changes',
      'Not individual-level data',
    ],
    citation: 'PLACES: Local Data for Better Health. Centers for Disease Control and Prevention.',
  },
  nci_sae: {
    id: 'nci_sae',
    name: 'NCI Small Area Estimates',
    abbreviation: 'NCI SAE',
    url: 'https://sae.cancer.gov/',
    description: 'County-level estimates of cancer-related risk factors and screening behaviors.',
    publisher: 'NCI',
    vintage: '2021-2022',
    releaseDate: '2024',
    geographyLevels: ['state', 'county'],
    updateFrequency: 'Periodic',
    limitations: [
      'Model-based estimates from NHIS/BRFSS',
      'County level only',
      'Confidence intervals can be wide for small counties',
    ],
    citation: 'NCI Small Area Estimates for Cancer-Related Measures. National Cancer Institute.',
  },
  ejscreen: {
    id: 'ejscreen',
    name: 'EJScreen: Environmental Justice Screening Tool',
    abbreviation: 'EJScreen',
    url: 'https://www.epa.gov/ejscreen',
    description: 'Block-group level environmental justice indicators: pollution burden, demographic indicators, EJ indexes.',
    publisher: 'EPA',
    vintage: '2024',
    releaseDate: '2024',
    geographyLevels: ['blockgroup', 'tract', 'county', 'state'],
    updateFrequency: 'Annual',
    limitations: [
      'Screening tool — not a risk assessment',
      'Some indicators are modeled or proxy-based',
      'Does not capture all environmental hazards',
    ],
    citation: 'EJScreen: Environmental Justice Screening and Mapping Tool. U.S. EPA.',
  },
  cdc_tracking: {
    id: 'cdc_tracking',
    name: 'CDC Environmental Public Health Tracking',
    abbreviation: 'CDC Tracking',
    url: 'https://ephtracking.cdc.gov/',
    description: 'Environmental hazard, exposure, and health outcome data linked in one system.',
    publisher: 'CDC',
    vintage: '2019-2023',
    releaseDate: '2025',
    geographyLevels: ['national', 'state', 'county'],
    updateFrequency: 'Annual',
    limitations: [
      'Not all states participate in all measures',
      'County-level data may have gaps',
      'Temporal coverage varies by measure',
    ],
    citation: 'CDC National Environmental Public Health Tracking Network.',
  },
  svi: {
    id: 'svi',
    name: 'Social Vulnerability Index',
    abbreviation: 'SVI',
    url: 'https://www.atsdr.cdc.gov/placeandhealth/svi/',
    description: 'Census-tract level social vulnerability ranking across 4 themes: socioeconomic, household composition, minority status, and housing/transportation.',
    publisher: 'CDC/ATSDR',
    vintage: '2022',
    releaseDate: '2024',
    geographyLevels: ['tract', 'county'],
    updateFrequency: 'Biennial (linked to ACS releases)',
    limitations: [
      'Relative vulnerability — not absolute risk',
      'Based on ACS which has sampling error',
      'Does not include health outcomes directly',
    ],
    citation: 'CDC/ATSDR Social Vulnerability Index.',
  },
  usda_fara: {
    id: 'usda_fara',
    name: 'Food Access Research Atlas',
    abbreviation: 'FARA',
    url: 'https://www.ers.usda.gov/data-products/food-access-research-atlas/',
    description: 'Tract-level indicators of low food access (food deserts), distance to supermarkets, vehicle access.',
    publisher: 'USDA ERS',
    vintage: '2019',
    releaseDate: '2021',
    geographyLevels: ['tract'],
    updateFrequency: 'Periodic',
    limitations: [
      'Based on 2019 SNAP retailer data and 2015-2019 ACS',
      'Does not capture all food retail (farmers markets, etc.)',
      'Binary low-access flag may oversimplify',
    ],
    citation: 'USDA Economic Research Service. Food Access Research Atlas.',
  },
  usda_fea: {
    id: 'usda_fea',
    name: 'Food Environment Atlas',
    abbreviation: 'FEA',
    url: 'https://www.ers.usda.gov/data-products/food-environment-atlas/',
    description: 'County-level food environment indicators: store availability, restaurant density, food assistance, food prices, food taxes, local food.',
    publisher: 'USDA ERS',
    vintage: '2020',
    releaseDate: '2022',
    geographyLevels: ['county', 'state'],
    updateFrequency: 'Periodic',
    limitations: [
      '300+ variables but vintage varies by indicator',
      'County level only',
      'Some indicators lag by several years',
    ],
    citation: 'USDA Economic Research Service. Food Environment Atlas.',
  },
  acs: {
    id: 'acs',
    name: 'American Community Survey (5-Year)',
    abbreviation: 'ACS',
    url: 'https://www.census.gov/programs-surveys/acs',
    description: 'Continuous demographic, social, economic, and housing survey. 5-year estimates available down to block group.',
    publisher: 'U.S. Census Bureau',
    vintage: '2020-2024',
    releaseDate: '2025-12',
    geographyLevels: ['national', 'state', 'county', 'tract', 'blockgroup', 'place', 'zcta'],
    updateFrequency: 'Annual (5-year rolling)',
    limitations: [
      'Sampling error grows at finer geographies',
      'Not a point-in-time census — rolling 5-year period',
      'Occupation codes are broad categories',
    ],
    citation: 'U.S. Census Bureau. American Community Survey 5-Year Estimates.',
  },
  epa_radon: {
    id: 'epa_radon',
    name: 'EPA Radon Zones',
    abbreviation: 'EPA Radon',
    url: 'https://www.epa.gov/radon/epa-map-radon-zones',
    description: 'County-level radon zone classification (Zones 1-3) based on indoor radon potential.',
    publisher: 'EPA',
    vintage: '1993 (static)',
    releaseDate: '1993',
    geographyLevels: ['county'],
    updateFrequency: 'Static / not regularly updated',
    limitations: [
      'Based on 1990s data',
      'County-level only — significant within-county variation',
      'Does not reflect actual home measurements',
    ],
    citation: 'EPA Map of Radon Zones. U.S. Environmental Protection Agency.',
  },
  nasa_power: {
    id: 'nasa_power',
    name: 'NASA POWER',
    abbreviation: 'NASA POWER',
    url: 'https://power.larc.nasa.gov/',
    description: 'Solar and meteorological data from satellite and model sources. Includes UV index and solar radiation at point/grid level.',
    publisher: 'NASA',
    vintage: '1981-2024',
    releaseDate: 'Continuous',
    geographyLevels: ['national', 'state', 'county'], // aggregated from grid
    updateFrequency: 'Near real-time',
    limitations: [
      'Satellite-derived — ground truth may differ',
      'Point/grid-based — must be aggregated to admin geographies',
      'UV index is modeled, not measured',
    ],
    citation: 'NASA Langley Research Center POWER Project.',
  },
};

export const getSourceById = (id: string): DataSource | undefined => DATA_SOURCES[id];

export const getSourcesByGeography = (level: string): DataSource[] =>
  Object.values(DATA_SOURCES).filter(s =>
    s.geographyLevels.includes(level as any)
  );
